[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

[dev]
  framework = "html"
  targetPort = 8000
  publish = "."

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
